import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { FLAG_CODES } from '../src/design/assets/flag-codes';

const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'node_modules', 'flag-icons', 'flags', '4x3');
const OUT = join(ROOT, 'public', 'brand', 'flags.svg');

/** flag-icons' files are self-contained SVGs whose inner ids ("a", "b", clipPaths…) repeat
 *  from flag to flag. One sprite = one id namespace, so every id and every reference to it is
 *  prefixed with the flag's code. The package names its files in lower-case; the sprite ids
 *  keep the upper-case code (W40). */
function toSymbol(code: string): string {
  const svg = readFileSync(join(SRC, `${code.toLowerCase()}.svg`), 'utf8');
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();
  const ns = inner
    .replace(/\sid="([^"]+)"/g, (_, id: string) => ` id="${code}-${id}"`)
    .replace(/url\(#([^)]+)\)/g, (_, id: string) => `url(#${code}-${id})`)
    .replace(
      /(xlink:)?href="#([^"]+)"/g,
      (_, x: string | undefined, id: string) => `${x ?? ''}href="#${code}-${id}"`,
    );
  return `<symbol id="flag-${code}" viewBox="0 0 640 480">${ns}</symbol>`;
}

export function buildFlagSprite(): string {
  const symbols = FLAG_CODES.map(toSymbol).join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n<!-- GENERATED by scripts/build-flags.ts from the flag-icons package (MIT). Do not edit; run: npm run assets:flags -->\n${symbols}\n</svg>\n`;
}

if (require.main === module) {
  writeFileSync(OUT, buildFlagSprite());
  console.log(`flags.svg: ${FLAG_CODES.length} flags → ${OUT}`);
}
